# .pre-commit-config.yaml
default_stages: [pre-commit]
repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.19.0
    hooks:
      - id: terraform-docs-system
        args: ["markdown", "-c", ".terraform-docs.yaml", "."]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: ".github/"
      - id: end-of-file-fixer
        exclude: ^.github/
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
