name: Bump tag and release version on MR
on:
  pull_request:
    types:
    - closed
    branches:
    - master
jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: sbpdvb
        WITH_V: true
        DEFAULT_BUMP: patch
    - name: Create release
      id: release
      uses: 
        Roang-zero1/github-create-release-action@57eb9bdce7a964e48788b9e78b5ac766cb684803 # v3.0.1
      with:
        created_tag: ${{ steps.tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
