name: Bump tag and release version on MR
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: "0"
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: sbpdvb
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Create release
        id: release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          created_tag: ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
